### PR TITLE
Enforce single quotes

### PR DESCRIPTION
**Pull request by joelmukuthu**
Depends on #31

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
Fixes #3. 

Needs to be a semver major. 

Is it fixable with `--fix`?

**Comment by joelmukuthu** [comment]
Yes it is :)

**Comment by joelmukuthu** [comment]
Btw I experienced some weird behaviour with the tests for this. Try to cause a failure in ~~[this code block](https://github.com/One-com/eslint-config-onelint/pull/26/commits/de2b511d26b94ac3b6f6eab743a7397a5127f587#diff-3e2b0c7f976c7bef57c962983301fea1R5)~~ [this code block](https://github.com/One-com/eslint-config-onelint/pull/26/files#diff-3e2b0c7f976c7bef57c962983301fea1R6) and then run the tests. The tests still pass even though you would expect them to fail, any idea why that happens?

**Comment by gustavnikolaj** [comment]
How did you alter the code block? What did it look like? :)

I'll try to reproduce and dig in.

**Comment by joelmukuthu** [comment]
I tried these:

``` js
var foo = 'foo'; // should have triggered an "unused variable" error
```

``` js
var foo = "foo"; // should have triggered an "only single quotes" error
```

And btw it was on node 6.6.0

**Comment by gustavnikolaj** [comment]
https://github.com/One-com/eslint-config-onelint/blob/04b9aa593871253f204328b087a159ccee4fefdc/test/util/md2js.js#L4

It's the parsing of the md files that break and fail to find the test case because of the backticks (template strings) in the code snippet.

We need to rebuild that regex to support template strings in the test cases.

**Comment by gustavnikolaj** [comment]
After landing #28 I have rebased and force pushed this branch. It now fails:

```
  1) documentation/quotes.md case 1:
     UnexpectedError: 
expected [ 'Line 7, column 8: Strings must use singlequote.' ] to equal []

[
  'Line 7, column 8: Strings must use singlequote.' // should be removed
]

      at documentation/quotes.md:19:8
      at Array.forEach (native)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace

```

**Comment by joelmukuthu** [comment]
As it turns out this won't work with eslint v2. I'll open another pull request for upgrading to v3

**Comment by gustavnikolaj** [comment]
@joelmukuthu What is it that will not work with eslint v2?

**Comment by joelmukuthu** [comment]
The ~~first~~ second example [here](http://eslint.org/docs/rules/quotes#avoidescape):

``` js
/*eslint quotes: ["error", "single", { "avoidEscape": true }]*/

var double = "a string containing 'single' quotes";
```

**Comment by gustavnikolaj** [comment]
So, neither one of the rules `"avoidEscape": true` nor `"avoid-escape": true` works in eslint 2.

**Comment by joelmukuthu** [comment]
Nope, neither of them do. Even linting the file fails when there is a config object for the quotes rule. See [here](https://travis-ci.org/One-com/eslint-config-onelint/builds/173837162#L320-L339)

**Comment by gustavnikolaj** [comment]
Rebased the branch and added the eslint 3 only option `avoidEscape`.

**Pull request merged**
